name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            rm -rf ~/spp-server || true
            mkdir ~/spp-server

            scp -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/spp-server/

            sudo fuser -k 8888/tcp || true

            cd ~/spp-server

            npm install

            nohup node server.js > server.log 2>&1 &
