name: Deploy Express Server

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Add your private SSH key in GitHub Secrets

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to your project directory on the EC2 instance
            cd spp-server

            # Pull the latest changes from GitHub
            git pull origin main

            # Install dependencies
            npm install

            # Restart the server using PM2
            pm2 restart all || pm2 start server.js --name "your-app-name"

            # Restart NGINX to apply any config changes (optional)
            sudo systemctl restart nginx
          EOF
